'use strict';
const $ = s => document.querySelector(s);
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon = name => `<i data-lucide="${name}" aria-hidden="true"></i>`;
const icons = () => lucide.createIcons({attrs: {width: 18, height: 18}});
const api = (m, ...a) => window.island.invoke(m, ...a);
let state, page = 'home', diskId, tab = 'overview', modalType = '', lastFocus, toastTimer, refreshing = false, queued = false, authKey = '', activeAuthId;
let folderId, folderPath = '', newMode = 'direct';
const bytes = v => {if (v == null) return '—'; if (!v) return '0 B'; const i = Math.min(4, Math.floor(Math.log(Math.max(v,1))/Math.log(1024))); return `${(v/1024**i).toFixed(i ? 1 : 0)} ${['B','KB','MB','GB','TB'][i]}`;};
const statuses = {unmounted:'未挂载',starting:'正在连接',mounted:'已挂载',stopping:'正在卸载',error:'需要处理'};
const modeName = d => d.mode === 'direct' ? '网盘直连' : '文件系统卷';
const serviceName = t => ({local:'本地文件夹',webdav:'WebDAV',s3:'S3 兼容存储',onedrive:'OneDrive',drive:'Google Drive',dropbox:'Dropbox'}[t] || '存储服务');
const connection = id => state.connections.find(c => c.id === id);
const button = (action, label, id = '', primary = false, disabled = false) => `<button class="${primary?'ir-primary':'ir-button'}" data-action="${action}" data-id="${escape(id)}" ${disabled?'disabled':''}>${label}</button>`;
const row = (name, value, note = '') => `<div class="ir-row"><div>${name}${note?`<small>${note}</small>`:''}</div><span class="ir-right">${value}</span></div>`;
function toast(message) {$('#toast').textContent = message; $('#toast').hidden = false; clearTimeout(toastTimer); toastTimer = setTimeout(() => $('#toast').hidden = true, 7000);}
function error(message) {if (!$('#overlay').hidden) {let el = $('#modal-error'); if (!el) {el = document.createElement('div'); el.id='modal-error'; el.className='inline-error'; $('#modal-content').append(el);} el.textContent = message;} else toast(message);}
async function action(fn) {try {return await fn();} catch(e) {error(e.message);}}
function openModal(type, html) {lastFocus=document.activeElement; modalType=type; $('#modal-content').innerHTML=html; $('#overlay').hidden=false; icons(); $('#modal-content').querySelector('input,select,button')?.focus();}
function closeModal() {modalType='';$('#overlay').hidden=true; lastFocus?.focus();}
const modalHead = (title,desc) => `<h2 id="modal-title">${title}</h2><p>${desc}</p>`;
const actions = (buttons) => `<div class="ir-dialogactions">${buttons}</div>`;
const cancel = () => button('cancel','取消');
function goto(name,id) {page=name; if(id)diskId=id; tab='overview';render();}
function pending(d) {const s=d.stats;if(d.status==='unmounted')return '挂载后即可使用';if(!s?.known)return '正在读取传输状态'; if(d.mode==='direct')return s.pendingFiles ? `${s.pendingFiles} 个文件待上传 · ${bytes(s.queuedBytes)}` : '上传队列已清空'; return s.pendingBlocks ? `${s.pendingBlocks} 个数据块待上传 · ${bytes(s.pendingBytes)}` : '无待上传数据块';}
function pill(d) {return `<span class="pill ${d.status==='mounted'?'green':d.status==='error'?'amber':''}">${d.status==='mounted'?'<b class="ir-dot"></b>':''}${statuses[d.status]||'未知'}</span>`;}
function driveCard(d) {return `<button class="ir-disk" data-action="detail" data-id="${d.id}"><div class="ir-diskheading"><span class="ir-hardware">${icon(d.mode==='direct'?'cloud':'layers')}</span>${pill(d)}</div><div class="ir-diskname"><h2>${escape(d.name)}</h2>${icon('chevron-right')}</div><div class="ir-desc">${d.letter} · ${escape(connection(d.connectionId)?.name)} · ${modeName(d)}</div><div class="ir-sync">${icon(d.stats?.pendingFiles||d.stats?.pendingBlocks?'cloud-upload':'check-circle-2')}<span>${pending(d)}</span></div></button>`;}
function title(name, desc, right='') {return `<div class="ir-titleline"><div><h1>${name}</h1><p>${desc}</p></div>${right}</div>`;}
function home() {
  let html = title('我的磁盘','让存储成为电脑的一部分。',button('add-disk',icon('plus')+' 添加磁盘','',true));
  if(!state.health.winfsp) html+=`<div class="errorbox">首次挂载需要安装磁盘驱动。安装完成后重新打开云屿。 ${button('driver','安装驱动')}</div>`;
  if(!state.disks.length) return html+`<div class="empty"><div class="empty-art">${icon('hard-drive')}<span class="small-cloud">${icon('cloud')}</span></div><h1>你的文件，就在手边</h1><p>连接一个网盘或本地文件夹，<br>将它挂载为电脑上的磁盘。</p>${button(state.connections.length?'add-disk':'add-connection',icon('plus')+(state.connections.length?' 创建第一个磁盘':' 添加存储连接'),'',true)}</div><div class="onboarding"><article><span>01</span><b>连接你的存储</b><p>账号和目录，统一管理。</p></article><article><span>02</span><b>选择使用方式</b><p>直接使用文件，或创建文件系统卷。</p></article><article><span>03</span><b>像磁盘一样使用</b><p>在资源管理器中打开、编辑与保存。</p></article></div>`;
  html += `<div class="ir-drives">${state.disks.map(driveCard).join('')}</div><div class="ir-section"><div class="ir-sectionhead"><h2>存储连接</h2><button class="ir-link" data-nav="connections">管理连接 ${icon('chevron-right')}</button></div><div class="ir-list">${state.connections.map(c=>row(`${escape(c.name)}`,serviceName(c.type),`${state.disks.filter(d=>d.connectionId===c.id).length} 个磁盘使用此连接`)).join('')}</div></div>`;
  return html;
}
function detail() {
  const d=state.disks.find(d=>d.id===diskId);if(!d){page='home';return home();}
  const s=d.stats, mounted=d.status==='mounted', active=d.status!=='unmounted';
  let html=`<div class="ir-detailhero"><div class="ir-detailname"><span class="ir-hardware">${icon(d.mode==='direct'?'cloud':'layers')}</span><div><h1>${escape(d.name)}</h1><p>${d.letter} · ${escape(connection(d.connectionId)?.name)} · ${modeName(d)}</p></div></div><div class="actions">${mounted?button('open','打开磁盘',d.id):''}${button(active?'unmount-confirm':'mount',active?'安全卸载':'挂载磁盘',d.id,!active,d.busy)}</div></div><div class="ir-segments">${[['overview','概览'],['cache','缓存'],['advanced','选项']].map(([id,t])=>`<button data-tab="${id}" aria-pressed="${tab===id}">${t}</button>`).join('')}</div>`;
  if(d.error||d.lastError)html+=`<div class="errorbox">${escape(d.error||d.lastError)}</div>`;
  if(tab==='overview')html+=`<div class="detail-summary"><div class="ir-detailcapacity"><div class="ir-desc">磁盘状态</div><div class="ir-number">${statuses[d.status]}</div><p style="margin-top:12px">挂载位置 ${d.letter}\\</p></div><div class="ir-detailcapacity"><div class="ir-desc">${d.mode==='direct'?'待上传文件':'待上传数据块'}</div><div class="ir-number">${s?.known?(d.mode==='direct'?s.pendingFiles:s.pendingBlocks):'—'}<small>${d.mode==='direct'?'个文件':'块'}</small></div><p style="margin-top:12px">${s?.known?bytes(d.mode==='direct'?s.queuedBytes:s.pendingBytes):'等待实时数据'}</p></div></div><div class="ir-section"><div class="ir-list">${row('存储连接',escape(connection(d.connectionId)?.name))}${row('使用方式',modeName(d))}${row('文件保存',d.mode==='direct'?'本地暂存后上传':d.writeback?'本地暂存后后台上传':'写入时提交远端')}${row('传输状态',pending(d))}</div></div><div class="ir-notice">${d.mode==='direct'?'文件关闭并空闲 5 秒后开始上传。请在队列清空后安全卸载。':'文件系统卷使用独立的数据目录；原网盘中的文件不会自动出现在此磁盘。元数据保存在这台电脑。'}</div>`;
  if(tab==='cache')html+=`<div class="ir-detailcapacity"><div class="ir-desc">本地缓存占用</div><div class="ir-number">${bytes(s?.known?s.cacheBytes:null)}<small>/ ${d.cacheGiB} GB 缓存目标</small></div><div class="ir-meter ir-spacebar"><span style="width:${Math.min(100,100*(s?.cacheBytes||0)/(d.cacheGiB*1024**3))}%"></span></div><p>最近访问的文件会自动保留，旧缓存由系统自动回收。</p></div><div class="ir-section"><div class="ir-list">${row('缓存目录',`<span class="path">${escape(d.paths.cache)}</span>`)}${row('空间管理','自动回收可下载的数据','待上传数据和正在使用的文件可能使占用超过缓存目标。')}${row('写入保护','保留待上传内容','此版本不提供手动删除缓存，避免误删尚未上传的数据。')}</div></div>`;
  if(tab==='advanced')html+=`<div class="ir-list">${row('后台上传',d.mode==='direct'?'关闭文件后开始':d.writeback?'开启':'关闭')}${row('当前用户访问','仅在当前 Windows 账户下管理')}${row('元数据',d.mode==='juicefs'?'保存在本机':'由存储服务管理')}</div><form id="disk-settings" class="ir-section"><div class="ir-list"><label class="ir-row"><span>启动时自动挂载</span><input name="autoMount" type="checkbox" class="ir-switch" ${d.autoMount?'checked':''} ${active?'disabled':''}></label><label class="ir-row"><span>缓存目标 <small>卸载后可以修改</small></span><input name="cacheGiB" type="number" min="1" max="2048" value="${d.cacheGiB}" class="ir-setting-input" style="width:110px" ${active?'disabled':''}></label></div><div class="ir-dialogactions">${button('save-disk-settings','保存设置',d.id,true,active)}</div></form><div class="ir-section"><div class="ir-list">${row('移除磁盘',button('remove-disk-confirm','移除…',d.id,false,active),'仅移除配置；远端文件、本地元数据与缓存会保留。')}</div></div>`;
  return html;
}
function activity() {
  let html=title('活动','查看这台电脑上的上传队列与传输状态。');
  const ds=state.disks.filter(d=>d.status!=='unmounted');
  if(!ds.length)return html+`<div class="empty">${icon('cloud-check')}<h1>现在没有传输任务</h1><p>挂载磁盘后，这里会显示实时上传状态。</p></div>`;
  for(const d of ds){const s=d.stats;html+=`<div class="ir-section"><div class="ir-sectionhead"><h2>${escape(d.name)} <span class="ir-discreet">${modeName(d)}</span></h2><span class="ir-right">${s?.known?bytes(s.speed)+'/s':'正在读取状态'}</span></div><div class="ir-list">`;
    if(!s?.known)html+=row('暂时无法确认传输状态','—','未将未知状态显示为“已上传”。');
    else if(d.mode==='juicefs')html+=row(pending(d),bytes(s.pendingBytes),'按数据块统计；不包含仍在应用程序中或内存中尚未提交的写入。');
    else if(!s.queue.length)html+=row('上传队列已清空',icon('check'),'尚未关闭的文件可能仍在写入。');
    else html+=s.queue.map(f=>{const t=s.transferring.find(t=>t.name===f.name);const percent=t&&t.size>0?Math.min(100,t.bytes/t.size*100):null;return `<div class="ir-row"><span class="ir-fileicon">${icon('file')}</span><div class="ir-filebody"><strong>${escape(f.name)}</strong>${percent===null?'':`<div class="progress-track"><div style="width:${percent}%"></div></div>`}<small>${bytes(f.size)}${f.tries>1?' · 正在重试':''}</small></div><span class="ir-right">${f.uploading?'正在上传':'等待上传'}</span></div>`;}).join('');html+='</div></div>';
  }return html;
}
function connections() {
  let html=title('存储连接','账号与文件夹，由磁盘按需使用。',button('add-connection',icon('plus')+' 添加连接','',true));
  if(!state.connections.length)return html+`<div class="empty"><div class="empty-art">${icon('cloud')}</div><h1>从一个连接开始</h1><p>在这里登录存储服务，或者选取本地文件夹。</p>${button('add-connection','添加存储连接','',true)}</div>`;
  return html+`<div class="ir-list">${state.connections.map(c=>`<div class="ir-row"><div class="ir-rowmain"><span class="service-glyph">${icon(c.type==='local'?'folder':'cloud')}</span><div><strong>${escape(c.name)}</strong><small>${serviceName(c.type)} · ${escape(c.localPath||c.folder||'/')}</small></div></div><div class="actions">${button('test-connection','检查',c.id)}${c.type!=='local'?button('folders','选择目录',c.id,false,state.disks.some(d=>d.connectionId===c.id)):''}${button('remove-connection-confirm','移除',c.id,false,state.disks.some(d=>d.connectionId===c.id))}</div></div>`).join('')}</div><div class="ir-notice">账号授权由云屿管理。登录凭据加密保存在当前电脑，不会发送到云屿服务器。</div>`;
}
function settings() {return title('设置','安静地工作，随时可用。')+`<div class="ir-sectionhead"><h2>通用</h2></div><div class="ir-list"><label class="ir-row"><span>登录 Windows 后启动</span><input type="checkbox" class="ir-switch" id="login-start" ${state.settings.loginStart?'checked':''}></label>${row('关闭窗口','继续在托盘运行')}${row('遥测与使用情况上报','关闭')}</div><div class="ir-section"><div class="ir-sectionhead"><h2>本机数据</h2></div><div class="ir-list">${row('账号与磁盘配置',button('open-data','打开数据目录'),'元数据、缓存与账号信息在此保存。请勿在运行中删除。')}${row('磁盘驱动',state.health.winfsp?'已检测到':button('driver','安装驱动'))}${row('安全退出',button('quit-confirm','退出云屿…'),'先关闭磁盘上的文件；上传未完成时保留后台运行。')}</div></div><div class="ir-section"><p>云屿 0.1.2 · Windows x64 预览版<br>文件系统卷目前面向单机使用。系统关机或断电前，请先完成上传。</p></div>`;}
function render() {if(!state)return; const names={home:'我的磁盘',activity:'活动',connections:'存储连接',settings:'设置',detail:state.disks.find(d=>d.id===diskId)?.name};$('#crumb').textContent='/ '+(names[page]||'我的磁盘');document.querySelectorAll('[data-nav]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.nav===(page==='detail'?'home':page))));$('#content').innerHTML=({home,detail,activity,connections,settings}[page]||home)();$('#shortcuts').innerHTML=state.disks.map(d=>`<button class="ir-shortcut" data-action="detail" data-id="${d.id}">${icon(d.mode==='direct'?'cloud':'layers')}<span>${escape(d.name)}</span><span class="ir-driveletter">${d.letter}</span></button>`).join('')||'<p style="padding:8px 11px;font-size:11px">还没有磁盘</p>';const speed=state.disks.reduce((n,d)=>n+(d.stats?.known?d.stats.speed||0:0),0);$('#total-status').textContent=speed?bytes(speed)+'/s':'传输活动';$('#foot-state').textContent=`本地管理 · ${state.disks.filter(d=>d.status==='mounted').length} / ${state.disks.length} 个磁盘已挂载`;const total=state.disks.reduce((n,d)=>n+(d.stats?.pendingFiles||d.stats?.pendingBlocks||0),0);$('#activity-badge').textContent=total||'';icons();}
function addConnection() {openModal('services',modalHead('添加存储连接','选择你的服务，账号授权由云屿完成。')+`<div class="service-grid">${state.services.map(s=>`<button class="service" data-service="${s.id}" ${s.available?'':'disabled'}>${icon(s.id==='local'?'folder':s.id==='s3'?'server':'cloud')}<span><strong>${s.name}</strong><small>${s.available?(s.id==='local'?'用于本地验证':s.id==='webdav'||s.id==='s3'?'使用账号与密钥连接':'通过浏览器安全登录'):'等待发布者开放登录'}</small></span></button>`).join('')}</div>`+actions(cancel()));}
function connectionForm(type) {const cloud=['onedrive','drive','dropbox'].includes(type);openModal('connection-form',modalHead('连接 '+serviceName(type),cloud?'将打开系统浏览器。云屿不会接触你的账户密码。':'填写连接信息，保存前会检查是否可访问。')+`<form id="connection-form" data-type="${type}"><label class="ir-field">连接名称<input class="ir-setting-input" name="name" required maxlength="48" value="${serviceName(type)}"></label>${type==='local'?`<label class="ir-field">本地文件夹<div class="actions"><input class="ir-setting-input" name="path" id="local-path" readonly placeholder="请选择文件夹">${button('pick-folder','选择…')}</div><small>可以使用一个空文件夹，验证磁盘读写流程。</small></label>`:cloud?'':`<label class="ir-field">服务地址<input class="ir-setting-input" name="url" type="url" required placeholder="https://storage.example.com"></label><label class="ir-field">${type==='s3'?'访问密钥':'用户名'}<input class="ir-setting-input" name="user" autocomplete="off"></label><label class="ir-field">${type==='s3'?'密钥密码':'密码'}<input class="ir-setting-input" name="password" type="password" autocomplete="off"></label>${type==='s3'?'<label class="ir-field">区域<input class="ir-setting-input" name="region" value="us-east-1"></label>':''}`}</form><div id="modal-error" class="inline-error"></div>`+actions(cancel()+button('submit-connection',cloud?'登录并授权':'连接存储','',true)));}
function showAuth(a) {if(!a)return;const key=[a.id,a.status,a.question?.label,a.error].join(':');if(key===authKey&&modalType==='auth')return;authKey=key;activeAuthId=a.id;let html=modalHead('连接 '+serviceName(a.service),'账号授权与设置由云屿统一管理。');if(a.status==='question'){const q=a.question;html+=`<label class="ir-field">${escape(q.label)}${q.choices.length?`<select class="ir-setting-input" id="auth-answer">${q.choices.map(o=>`<option value="${escape(o.value)}" ${o.value===q.value?'selected':''}>${escape(o.label)}</option>`).join('')}</select>`:`<input id="auth-answer" class="ir-setting-input" type="${q.password?'password':'text'}" value="${escape(q.value)}">`}</label>${a.error?`<div class="inline-error">${escape(a.error)}</div>`:''}`+actions(button('cancel-auth','取消连接')+button('answer-auth','继续','',true));}
else if(a.status==='error')html+=`<div class="errorbox">${escape(a.error)}</div>`+actions(button('cancel-auth','返回'));
else html+=`<div class="auth-wait"><span class="spinner"></span><strong>${a.status==='authorizing'?'请在浏览器中完成登录':a.status==='checking'?'正在检查存储访问':'正在连接账户'}</strong><p>${a.status==='authorizing'?'授权完成后会自动返回下一步。':'通常只需要几秒钟。'}</p></div>`+actions(button('cancel-auth','取消连接'));openModal('auth',html);}
function addDisk(){if(!state.connections.length){addConnection();return;}newMode='direct';const available='XYZWVUTSRQPONMLKJIHGFED'.split('').map(x=>x+':').filter(l=>!state.disks.some(d=>d.letter===l));openModal('add-disk',modalHead('添加磁盘','选择使用方式，再把存储放到电脑上。')+`<div class="ir-typechoices"><button data-mode="direct" aria-pressed="true">${icon('cloud')}网盘直连<small>直接使用网盘中已有的文件</small></button><button data-mode="juicefs" aria-pressed="false">${icon('layers')}文件系统卷<small>新建独立卷，保留文件系统语义</small></button></div><form id="add-disk-form"><label class="ir-field">存储连接<select name="connectionId" class="ir-setting-input">${state.connections.map(c=>`<option value="${c.id}">${escape(c.name)}</option>`).join('')}</select></label><div class="ir-two"><label class="ir-field">磁盘名称<input name="name" class="ir-setting-input" value="我的磁盘" required maxlength="48"></label><label class="ir-field">盘符<select name="letter" class="ir-setting-input">${available.map(l=>`<option>${l}</option>`).join('')}</select></label></div><label class="ir-field">缓存目标（GB）<input name="cacheGiB" type="number" min="1" max="2048" value="10" class="ir-setting-input"></label><label class="checkbox"><input name="autoMount" type="checkbox">启动时自动挂载</label><div id="volume-options" hidden><label class="checkbox"><input name="writeback" type="checkbox">开启本地暂存与后台上传</label><small class="muted">开启后，未上传的数据依赖这台电脑。默认关闭。</small><div class="ir-notice">将在所选存储中创建独立的数据目录，原有文件不会自动导入。卷的元数据保存在当前电脑。</div></div></form><div id="modal-error" class="inline-error"></div>`+actions(cancel()+button('create-disk','创建磁盘','',true)));}
async function folders(id,relative=''){folderId=id;folderPath=relative;openModal('folders',modalHead('选择存储目录','选择此连接要使用的文件夹。')+'<div class="auth-wait"><span class="spinner"></span></div>');const list=await api('listFolders',id,relative);if(modalType!=='folders'||folderId!==id)return;$('#modal-content').innerHTML=modalHead('选择存储目录','选择此连接要使用的文件夹。')+`<div class="ir-notice">/${escape(relative)}</div><div class="folder-list">${relative?`<button data-folder="${escape(relative.split('/').slice(0,-1).join('/'))}">${icon('arrow-up')}上一级</button>`:''}${list.map(f=>`<button data-folder="${escape(f.path)}">${icon('folder')}${escape(f.name)}</button>`).join('')||'<p style="padding:16px">此目录下没有子文件夹。</p>'}</div>`+actions(cancel()+button('choose-folder','使用此目录','',true));icons();}
async function refresh(){if(refreshing){queued=true;return;}refreshing=true;try{state=await api('snapshot');const focused=document.activeElement;const editing=$('#content').contains(focused)&&['INPUT','SELECT','TEXTAREA'].includes(focused?.tagName);if(!editing)render();if(state.auth)showAuth(state.auth);else if(modalType==='auth'&&activeAuthId){const id=activeAuthId;activeAuthId=null;authKey='';closeModal();if(state.connections.some(c=>c.id===id)){toast('存储已连接');page='connections';render();await folders(id);}}}catch(e){toast(e.message);}finally{refreshing=false;if(queued){queued=false;refresh();}}}
document.addEventListener('submit',e=>e.preventDefault());
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;action(async()=>{
  if(b.dataset.nav){goto(b.dataset.nav);return;}if(b.dataset.tab){tab=b.dataset.tab;render();return;}if(b.dataset.service){connectionForm(b.dataset.service);return;}if(b.dataset.mode){newMode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('#volume-options').hidden=newMode!=='juicefs';return;}if(b.dataset.folder!==undefined){await folders(folderId,b.dataset.folder);return;}
  const id=b.dataset.id;
  switch(b.dataset.action){
    case 'cancel':closeModal();break;
    case 'add-connection':addConnection();break;
    case 'pick-folder':{const p=await api('pickFolder');if(p)$('#local-path').value=p;break;}
    case 'submit-connection':{const f=$('#connection-form');if(!f.reportValidity())break;const input=Object.fromEntries(new FormData(f));input.type=f.dataset.type;b.disabled=true;try{if(input.type==='local'){await api('addLocal',input);closeModal();page='connections';toast('本地文件夹已连接');}else{await api('connect',input);$('#connection-form')?.reset();}await refresh();}finally{b.disabled=false;}break;}
    case 'answer-auth':await api('answerAuth',state.auth.id,$('#auth-answer').value);await refresh();break;
    case 'cancel-auth':b.disabled=true;try{await api('cancelAuth');activeAuthId=null;closeModal();await refresh();}finally{b.disabled=false;}break;
    case 'add-disk':addDisk();break;
    case 'create-disk':{const f=$('#add-disk-form');if(!f.reportValidity())break;const v=Object.fromEntries(new FormData(f));v.mode=newMode;v.cacheGiB=Number(v.cacheGiB);v.autoMount=f.autoMount.checked;v.writeback=f.writeback.checked;b.disabled=true;try{const newId=await api('addDisk',v);closeModal();page='detail';diskId=newId;tab='overview';await refresh();toast('磁盘已创建，点击“挂载磁盘”开始使用');}finally{b.disabled=false;}break;}
    case 'detail':goto('detail',id);break;
    case 'mount':b.disabled=true;toast('正在挂载磁盘…');await api('mount',id);await refresh();toast('磁盘已挂载');break;
    case 'open':await api('openDisk',id);break;
    case 'unmount-confirm':openModal('confirm',modalHead('安全卸载磁盘？','请先关闭使用此磁盘的文件和程序。未完成的上传会阻止卸载；不会强制结束磁盘进程。')+actions(cancel()+button('unmount','安全卸载',id,true)));break;
    case 'unmount':b.disabled=true;try{await api('unmount',id);closeModal();await refresh();toast('磁盘已卸载');}finally{b.disabled=false;}break;
    case 'save-disk-settings':{const f=$('#disk-settings');await api('updateDisk',id,{autoMount:f.autoMount.checked,cacheGiB:Number(f.cacheGiB.value)});await refresh();toast('设置已保存');break;}
    case 'test-connection':b.disabled=true;try{await api('testConnection',id);toast('连接正常，可以访问此目录');}finally{b.disabled=false;}break;
    case 'folders':await folders(id);break;
    case 'choose-folder':await api('setFolder',folderId,folderPath);closeModal();await refresh();toast('存储目录已选择');break;
    case 'remove-connection-confirm':openModal('confirm',modalHead('移除存储连接？','仅移除这台电脑上的账号配置，存储服务中的文件会保留。')+actions(cancel()+button('remove-connection','移除',id)));break;
    case 'remove-connection':await api('deleteConnection',id);closeModal();await refresh();break;
    case 'remove-disk-confirm':openModal('confirm',modalHead('移除此磁盘？','磁盘将从列表中移除。远端内容、本地缓存和元数据都会保留在数据目录中。')+actions(cancel()+button('remove-disk','移除',id)));break;
    case 'remove-disk':await api('removeDisk',id);closeModal();goto('home');await refresh();break;
    case 'open-data':await api('openData');break;
    case 'driver':await api('installDriver');break;
    case 'quit-confirm':openModal('confirm',modalHead('安全退出云屿？','请先关闭磁盘上的文件。所有磁盘卸载完成后，云屿才会退出。')+actions(cancel()+button('quit','安全退出','',true)));break;
    case 'quit':b.disabled=true;await api('quit');b.disabled=false;closeModal();break;
  }
});});
document.addEventListener('change',e=>{if(e.target.id==='login-start')action(()=>api('settings',{loginStart:e.target.checked}));});
document.addEventListener('keydown',e=>{if($('#overlay').hidden)return;if(e.key==='Escape'&&modalType!=='auth')closeModal();if(e.key==='Tab'){const a=[...$('#modal-content').querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled)')];if(!a.length)return;const first=a[0],last=a.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.island.onChange(refresh);icons();refresh();
